export const RELATIONSHIP_OPTIONS = [
  'De Facto Partner',
  'De Facto Husband',
  'De Facto Wife',
  'Husband',
  'Partner',
  'Sibling',
  'Spouse',
  'Wife',
  'Aunt',
  'Brother',
  'Brother-In-Law',
  'Child',
  'Cousin',
  'Daughter',
  'Daughter-In-Law',
  'Domestic Partner',
  'Executor of the Estate',
  'Ex-Husband',
  'Ex-Wife',
  'Ex-Partner',
  'Father',
  'Father-In-Law',
  'Friend',
  'Godchild',
  'Goddaughter',
  'Godson',
  'Godfather',
  'Godmother',
  'Godparent',
  'Grandchild',
  'Granddaughter',
  'Grandson',
  'Great-Grandchild',
  'Mother',
  'Mother-In-Law',
  'Nephew',
  'Niece',
  'Sister',
  'Sister-In-Law',
  'Solicitor',
  'Son',
  'Son-In-Law',
  'Step-Brother',
  'Step-Daughter',
  'Step-Child',
  'Step-Father',
  'Step-Mother',
  'Step-Parent',
  'Step-Sibling',
  'Step-Sister',
  'Step-Son',
  'Uncle',
  'Accountant',
  'Financial Manager',
  'Attorney',
];
