// Document Templates with Variable Placeholders
// Variables follow Clio format: << VariableName >>
// Mappings defined in templateEngine.ts

export const TEMPLATES = {
  simple_will_individual: `Last Will of<< Matter.Client.Name >> Prepared by<< Firm.Name >><< Firm.Address >>T: << Firm.Phone >>E: << Firm.Email >>Ref: <<Matter.OriginatingAttorney.Initials>>:<<Matter.ClientReferenceNumber>>Last Will of << Matter.Client.Name >>of << Matter.Client.Address >>: GENERALIntentionsI, << Matter.Client.Name >>:revoke all former wills and other testamentary acts made by me; declare this to be my last Will; andconfirm PART E and PART F titled 'interpretation' and 'definitions' apply in relation to the interpretation of this Will.: TESTAMENTARY DIRECTIONSExecutor and trusteeI appoint as the executor and trustee of my Will:<< Matter.CustomField.InitialExecutor >>;if << Matter.CustomField.InitialExecutor >> is unable or unwilling to act for any reason, then I appoint << Matter.CustomField.BackupExecutor >>; orif << Matter.CustomField.BackupExecutor >> is unable or unwilling to act for any reason, then I appoint << Matter.CustomField.FurtherBackupExecutor >>.Unless otherwise specifically stated in my Will:my Executor is not excluded from participating in any matter concerning the administration of my estate only because of a personal interest in the matter;a gift to a person named in the preceding sub-clause is not dependent on that person acting as my Executor; andthe words 'unable or unwilling to act' in relation to any person named as an Executor includes any scenario where that person:declines to act;is disqualified from acting pursuant to the terms of this Will or at law; is unable to complete the administration of my estate for any reason; or if the appointment otherwise fails for any reason, either before they accept the role or at any time while they hold the role.Testamentary guardian for MinorsIf there is no surviving guardian of my Minor Children, then I appoint:<< Matter.CustomField.InitialGuardian >>; orif << Matter.CustomField.InitialGuardian >> is unable or unwilling to act for any reason, then I appoint << Matter.CustomField.BackupGuardian >>.`,
  simple_will_couple: `Last Will of<< Matter.Relationships.Mr.Name >>Prepared by<< Firm.Name >><< Firm.Address >>T: << Firm.Phone >>E: << Firm.Email >>Ref: <<Matter.OriginatingAttorney.Initials>>:<<Matter.ClientReferenceNumber>>Last Will of << Matter.Relationships.Mr.Name >>of << Matter.Client.Address >>: GENERALIntentionsI, << Matter.Relationships.Mr.Name >>:revoke all former wills and other testamentary acts made by me; declare this to be my last Will; andconfirm PART E and PART F titled 'interpretation' and 'definitions' apply in relation to the interpretation of this Will.: TESTAMENTARY DIRECTIONSExecutor and trusteeI appoint as the executor and trustee of my Will:<< Matter.CustomField.InitialExecutor >>;if << Matter.CustomField.InitialExecutor >> is unable or unwilling to act for any reason, then I appoint << Matter.CustomField.BackupExecutor >>; orif << Matter.CustomField.BackupExecutor >> is unable or unwilling to act for any reason, then I appoint << Matter.CustomField.FurtherBackupExecutor >>.`,
  single_tt_will_individual: `Last Will of<< Matter.Client.Name >>Prepared by<< Firm.Name >><< Firm.Address >>T: << Firm.Phone >>E: << Firm.Email >>Ref: <<Matter.OriginatingAttorney.Initials>>:<<Matter.ClientReferenceNumber>>Last Will of << Matter.Client.Name >>of << Matter.Client.Address >>: GENERALIntentionsI:revoke all former wills and other testamentary acts made by me; declare this to be my last Will; andconfirm PART E and PART F titled 'interpretation' and 'definitions' apply in relation to the interpretation of this Will.`,
  single_tt_will_couple: `Last Will of<< Matter.Relationships.Mr.Name >>Prepared by<< Firm.Name >><< Firm.Address >>T: << Firm.Phone >>E: << Firm.Email >>Ref: <<Matter.OriginatingAttorney.Initials>>:<<Matter.ClientReferenceNumber>>Last Will of << Matter.Relationships.Mr.Name >>of << Matter.Client.Address >>: GENERALIntentionsI:revoke all former wills and other testamentary acts made by me; declare this to be my last Will; andconfirm PART E and PART F titled 'interpretation' and 'definitions' apply in relation to the interpretation of this Will.`,
  multi_tt_will_individual: `Last Will of<< Matter.Client.Name >>Prepared by<< Firm.Name >><< Firm.Address >>T: << Firm.Phone >>E: << Firm.Email >>Ref: <<Matter.OriginatingAttorney.Initials>>:<<Matter.ClientReferenceNumber>>Last Will of << Matter.Client.Name >>of << Matter.Client.Address >>: GENERALIntentionsI, << Matter.Client.Name >>:revoke all former wills and other testamentary acts made by me; declare this to be my last Will; andconfirm PART E and PART F titled 'interpretation' and 'definitions' apply in relation to the interpretation of this Will.; declare this to be my last Will.`,
  multi_tt_will_couple: `Last Will of<< Matter.Relationships.Mr.Name >>Prepared by<< Firm.Name >><< Firm.Address >>T: << Firm.Phone >>E: << Firm.Email >>Ref: <<Matter.OriginatingAttorney.Initials>>:<<Matter.ClientReferenceNumber>>Last Will of << Matter.Relationships.Mr.Name >>of << Matter.Client.Address >>: GENERALIntentionsI, << Matter.Relationships.Mr.Name >>:revoke all former wills and other testamentary acts made by me; declare this to be my last Will; andconfirm PART E and PART F titled 'interpretation' and 'definitions' apply in relation to the interpretation of this Will.`,
};

export const FIRM_INFO = {
  name: 'St Ives Law',
  address: 'St Ives Law Address',
  phone: '(02) 1234 5678',
  email: 'info@stiveslaw.com.au',
};

export type TemplateType = 'simple_will' | 'single_tt_will' | 'multi_tt_will';
export type ScenarioType = 'individual' | 'couple';
